name: Testes Regressivos Devops Qazando - Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome*.deb

      - name: Instalar ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          java -version
          mvn -version

      - name: Rodar os testes
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar Relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar Relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/formated-report/"

      - name: Enviar notificação para o Slack - SUCESSO
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: devops-qazando
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://icon2.cleanpng.com/20171221/lle/success-png-image-5a3c42bdc288a6.4170951415138986857968.jpg
          SLACK_MESSAGE: 'Testes de regressão executados com sucesso! :white_check_mark:'
          SLACK_TITLE: 'Testes de regressão executados com sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação para o Slack - FALHA
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: devops-qazando
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148766.png
          SLACK_MESSAGE: 'Erro ao executar testes de regressão! :fire:'
          SLACK_TITLE: 'Erro ao executar testes de regressão! :fire:'
          SLACK_USERNAME: ERRO